### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by LoveIsAGame** [NVlabs/wetectron#33]
Thank you very much for your excellent work!
I've been trying to run your code recently, and every time I start the training code, there will be a problem as shown in the figure below.
All configuration files and pkl files are downloaded from the page you provide.
Can you tell me what's wrong?
Looking forward to your reply!

I don't know why my GitHub can't upload pictures. I copied the printed information below!The last line is the error message.

loading annotations into memory...
datasets\coco/annotations/instances_train2014.json
Done (t=13.19s)
creating index...
index created!
Loading proposals from: proposal/MCG-coco_2014_train-boxes.pkl
2021-01-10 14:34:22,395 wetectron.utils.miscellaneous INFO: Saving labels mapping into training\labels.json
2021-01-10 14:34:22,517 wetectron.trainer INFO: Start training
Traceback (most recent call last):
  File "tools/train_net.py", line 301, in <module>
    main()
  File "tools/train_net.py", line 280, in main
    use_tensorboard=args.use_tensorboard
  File "tools/train_net.py", line 92, in train
    meters
  File "d:\year2020\wetectron-master\wetectron\engine\trainer.py", line 73, in do_train
    for iteration, (images, targets, rois, _) in enumerate(data_loader, start_iter):
  File "D:\anaconda2019\lib\site-packages\torch\utils\data\dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "D:\anaconda2019\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
    w.start()
  File "D:\anaconda2019\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\anaconda2019\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda2019\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda2019\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda2019\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
OSError: [Errno 22] Invalid argument
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\anaconda2019\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "D:\anaconda2019\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
_pickle.UnpicklingError: pickle data was truncated

**Comment by jason718** [comment]
I have no clue, doesn't seem to be a problem of this code.

What would happen if you load the *.pkl from your python cmd?

**Comment by LoveIsAGame** [comment]
The test code is normal, and there are also pkl files in the test code~
